### ISSUE TITLE
RFC3339 Doesn't work with Time offset

### ISSUE THREAD

**Issue by jamesontriplett** [raml-org/raml-examples#14]
I'm putting an example of a RFC3339 compliant Time Code with a Timezone Offset in my RAML example and as far as I can tell it is RFC3339 complient, except that RAML says it's a bad date-time.  

      orderDate?: 
        type: datetime
        example: 2016-02-28T16:41:41-4:00
        format: rfc3339 

According to RFC documentation examples, this is valid:
```      
1996-12-19T16:39:57-08:00
   This represents 39 minutes and 57 seconds after the 16th hour of
   December 19th, 1996 with an offset of -08:00 from UTC (Pacific
   Standard Time).  Note that this is equivalent to 1996-12-20T00:39:57Z
   in UTC.```

**Comment by jstoiko** [comment]
when you say:
> except that RAML says it's a bad date-time
I'm assuming you mean a RAML parser/processor in which case this is not an issue with RAML but with such parser/processor. Can you raise an issue on the corresponding github repository then?
