### ISSUE TITLE
Problem with discriminator property in typesystem/complex.raml example

### ISSUE THREAD

**Issue by constint** [raml-org/raml-examples#4]
In example [typesystem/complex.raml](https://github.com/raml-org/raml-examples/blob/master/typesystem/complex.raml), there are two problematic properties in the body : 
`kind: admin`
`kind: manager`

The issue was noticed using version [1.0.0](https://github.com/raml-org/raml-java-parser/tree/1.0.0) of the [raml-java-parser](https://github.com/raml-org/raml-java-parser), as parsing the example fails with the following errors:

```
- message: "Invalid type name: admin"
- message: "Invalid type name: manager"
```

After reading the spec, it seems to me that the example should either use the discriminatorValue facet in the Admin and Manager type declaration, or use uppercase for `admin` and `manager` when discriminating between the types.

**Comment by naterkane** [comment]
https://github.com/raml-org/raml-examples/pull/7
