### ISSUE TITLE
Please create one example file containing all possible items

### ISSUE THREAD

**Issue by cascer1** [raml-org/raml-examples#5]
I'm working on a tool that will generate printable PDF documents from a RAML spec and would love to have one 'definitive' file I can use that implements all elements available in RAML. Being able to successfully render this test file would indicate that the tool works properly.

**Comment by sichvoge** [comment]
I tried to do that with https://github.com/raml-org/raml-examples/tree/master/others/world-music-api. Have a look at let me know what you think.

**Comment by cascer1** [comment]
Welp, looks like my tool has quite a ways to go! Thanks :smile:

**Comment by sichvoge** [comment]
Whats the link to your tool?

**Comment by cascer1** [comment]
My boss (I'm doing it as part of an internship) wants to keep it closed source until it's developed further. The current version (kind of cheating using just `.toJSON()` and giving that to Nunjucks) doesn't support any inheritance using stuff like `is:` or `type:`. If someone would want to participate in development I could convince them to let me open-source it sooner.

**Comment by sichvoge** [comment]
No worries. I will wait patiently ;)
