### ISSUE TITLE
Broken example in world-music-api?

### ISSUE THREAD

**Issue by kevinrenskers** [raml-org/raml-examples#6]
The `/entry` type is `collection` (https://github.com/raml-org/raml-examples/blob/master/others/world-music-api/api.raml#L170)

That type refers to a schema `<<resourcePathName|!singularize|!uppercamelcase>>` but there is no such schema in this repo (https://github.com/raml-org/raml-examples/blob/master/others/world-music-api/api.raml#L60-L68).

**Comment by sichvoge** [comment]
It should point to `Entry` but the parser does not support piping functions yet.
