### ISSUE TITLE
If I am following the banking-api example, how do I add examples per endpoint?

### ISSUE THREAD

**Issue by partounian** [raml-org/raml-examples#9]
First of all thank you for adding the amazing banking-api example. My question is if I'm following that structure what is best practice for per-endpoint examples for the type system. For example, we have this.
```raml
post:
  description: Creates <<resourcePathName | !singularize>> data
  responses:
    201:
      body:
        application/json:
          type: <<get-response-type>>
```
with
```raml
/users:
  type:
    member:
      post-request-type: types.thing
  post:
```

For solutions I have tried:
```raml
/users:
  type:
    member:
      post-request-type: types.thing
        example:
          user: Patrick
          password: securepass       
  post:
```
and
```raml
/users:
  type:
    member:
      post-request-type: types.thing
  post:
    example:
      user: Patrick
      password: securepass 
```

**Comment by sichvoge** [comment]
What I would probably do is to introduce a parameter for examples in resource types. For example, take the following snippet from the member.raml resource type fragment:

```yaml
get:
  is: [ traits.partial ]
  description: Returns <<resourcePathName | !singularize>> data
  responses:
    200:
      body:
        application/json:
          type: <<get-response-type>>
          example: <<get-response-example>>
```

I only added `example: <<get-response-example>>` and now if you apply the member resource type, you also have to provide information for the `get-response-example` parameter. Meaning:

```yaml
/users:
  type:
    member:
      get-response-type: types.thing
      get-response-example: 
        user: Patrick
        password: securepass
```

**Comment by partounian** [comment]
Awesome thank you! I had a feeling it would be something along the lines of another variable, but I didn't realize it could take an object like that.

**Comment by partounian** [comment]
So that worked, but now my problem is what if I want the example to be optional?
`example?: <<get-response-example>>` throws and unknown facet error.

**Comment by sichvoge** [comment]
That's not possible indeed. The only possibility in this case is to override the response like that:

```yaml
/users:
  type:
    member:
      get-response-type: thing
  get:
    responses: 
      200:
        body: 
          application/json:
            example:
              user: Patrick
              password: securepass
```

Of course, you would need to remove `example` from the resource type definition. Now you can handle examples on a case by case basis.
